# Generated by Django 6.0.3 on 2026-04-29 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='familydata',
            table='family_data',
        ),
    ]
