# Generated by Django 6.0.3 on 2026-05-06 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_familydata_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='familydata',
            name='income',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='ExpensesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('expense', models.FloatField()),
                ('date', models.DateField(blank=True, null=True)),
                ('family_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.familydata')),
            ],
        ),
    ]
